export const winners = [
    {
        id: 0,
        team_name : "The System Squads",
        dept : "CSE",
        year : "2",
        img : "images/System Squads.jpg",
        prize_category : "OPEN INNOVATION CATEGORY",
        Team_Members_1 : "Sharath P",
        Team_Members_2 : "Srinidhi R",
        Team_Members_3 : "Shwetaharini S",
        Team_Members_4 : "Suganth M",
        Team_Members_5 : "Selvakumar S",
    },
    {
        id: 1,
        team_name : "USBee",
        dept : "CSE",
        year : "1",
        img : "images/Usbee.jpg",
        prize_category : "CROP DISEASE IDENTIFICATION",
        Team_Members_1 : "Sneha Janarthanan",
        Team_Members_2 : "Siddhesh Agarwal",
        Team_Members_3 : "Yashu Venkat S",
        Team_Members_4 : "Sunil Kishore C",
        Team_Members_5 : "Navadeesh S",
    },
    {
        id: 2,
        team_name : "HackHers",
        dept : "CSE",
        year : "1",
        img : "images/HackHers.jpg",
        prize_category : "EDUCATIONAL GAMES",
        Team_Members_1 : "Prithika Andrea Angelina",
        Team_Members_2 : "Madhumitha R",
        Team_Members_3 : "Pratiba S",
        Team_Members_4 : "Monisha K",
        Team_Members_5 : "Priyadharshini U",
    },
    {
        id: 3,
        team_name : "Crew X",
        dept : "ECE",
        year : "1",
        img : "images/CrewX.jpg",
        prize_category : "OPEN INNOVATION CATEGORY",
        Team_Members_1 : "Arvind S",
        Team_Members_2 : "Yuvan S",
        Team_Members_3 : "Subasri P",
        Team_Members_4 : "Suhaina A",
        Team_Members_5 : "SujithKumar N",
    },
    {
        id: 4,
        team_name : "Mechatronz",
        dept : "MCT",
        year : "1",
        img : "images/Mechartanz.jpg",
        prize_category : "SUSTAINABILITY",
        Team_Members_1 : "Amrit Balaji",
        Team_Members_2 : "Abdul wahid",
        Team_Members_3 : "Boobesh Kumar",
        Team_Members_4 : "Chandru",
        Team_Members_5 : "Annamalai samy",
    },
    {
        id: 5,
        team_name : "TECHNOCRATS",
        dept : "AI&DS CSE",
        year : "2",
        img : "images/Technocrats.jpg",
        prize_category : "EDUCATIONAL GAMES",
        Team_Members_1 : "PRABITHA P",
        Team_Members_2 : "SAPARNA K",
        Team_Members_3 : "SANTHIYA A",
        Team_Members_4 : "ANU KIRUTHIGA R",
        Team_Members_5 : "DEEPA SHARANYA S",
    },
    {
        id: 6,
        team_name : "A2Z Techvalley",
        dept : "CSBS",
        year : "1",
        img : "images/A2Z Tech Valley.jpg",
        prize_category : "OPEN INNOVATION CATEGOR",
        Team_Members_1 : "Vishal Chinnasamy",
        Team_Members_2 : "Sasidharan Ramachandran",
        Team_Members_3 : "Rathi Raguraman",
        Team_Members_4 : "Christina Mercy Mathew",
        Team_Members_5 : "",
    },
    {
        id: 7,
        team_name : "Broskis",
        dept : "IT",
        year : "1",
        img : "images/Brosikis.jpg",
        prize_category : "OPEN INNOVATION CATEGORY",
        Team_Members_1 : "Rishikesh S",
        Team_Members_2 : "Sriram M",
        Team_Members_3 : "Shyam J",
        Team_Members_4 : "Suraj V",
        Team_Members_5 : "Tharun Deeksith K",
    },
    {
        id: 8,
        team_name : "HACK SQUAD HA^3",
        dept : "IT",
        year : "1",
        img : "images/Hacksquad.jpg",
        prize_category : "OPEN INNOVATION CATEGORY",
        Team_Members_1 : "Harini P",
        Team_Members_2 : "Almitha Dency J",
        Team_Members_3 : "Archana M",
        Team_Members_4 : "Arthi S",
        Team_Members_5 : "Harini P",
    },
      
  ];
  