export const winners = [
  {
    id: 0,
    team_name: "The System Squads",
    img: "images/System Squads.jpg",
    prize_category: "Best Design Hack",
    Team_Members_1: "Sharath P",
    Team_Members_2: "Srinidhi R",
    Team_Members_3: "Shwetaharini S",
    Team_Members_4: "Suganth M",
    Team_Members_5: "Selvakumar S",
  },
  {
    id: 1,
    team_name: "USBee",
    img: "images/Usbee.jpg",
    prize_category: "Most Sustainable Hack",
    Team_Members_1: "Sneha Janarthanan",
    Team_Members_2: "Siddhesh Agarwal",
    Team_Members_3: "Yashu Venkat S",
    Team_Members_4: "Sunil Kishore C",
    Team_Members_5: "Navadeesh S",
  },
  {
    id: 2,
    team_name: "HackHers",
    img: "images/HackHers.jpg",
    prize_category: "Best Community Hack",
    Team_Members_1: "Prithika Andrea Angelina",
    Team_Members_2: "Madhumitha R",
    Team_Members_3: "Prathiba S",
    Team_Members_4: "Monisha K",
    Team_Members_5: "Priyadharshini U",
  },
  {
    id: 3,
    team_name: "Crew X",
    img: "images/CrewX.jpg",
    prize_category: "Best Beginner Hack",
    Team_Members_1: "Arvind S",
    Team_Members_2: "Yuvan S",
    Team_Members_3: "Subasri P",
    Team_Members_4: "Suhaina A",
    Team_Members_5: "SujithKumar N",
  },
  {
    id: 4,
    team_name: "Mechatronz",
    img: "images/Mechartanz.jpg",
    prize_category: "Most Impressive Hack",
    Team_Members_1: "Amrit Balaji",
    Team_Members_2: "Abdul wahid",
    Team_Members_3: "Boobesh Kumar",
    Team_Members_4: "Chandru",
    Team_Members_5: "Annamalai samy",
  },
  {
    id: 5,
    team_name: "TECHNOCRATS",
    img: "images/Technocrats.jpg",
    prize_category: "Best Game Hack",
    Team_Members_1: "Prabitha P",
    Team_Members_2: "Saparna K",
    Team_Members_3: "Santhiya A",
    Team_Members_4: "Anu Kiruthiga R",
    Team_Members_5: "Deepa Sharanya S",
  },
  {
    id: 6,
    team_name: "A2Z Techvalley",
    img: "images/A2Z Tech Valley.jpg",
    prize_category: "Most Creative Hack",
    Team_Members_1: "Vishal Chinnasamy",
    Team_Members_2: "Sasidharan Ramachandran",
    Team_Members_3: "Rathi Raguraman",
    Team_Members_4: "Christina Mercy Mathew",
    Team_Members_5: "",
  },
  {
    id: 7,
    team_name: "Broskis",
    img: "images/Brosikis.jpg",
    prize_category: "Most Impactful Hack",
    Team_Members_1: "Rishikesh S",
    Team_Members_2: "Sriram M",
    Team_Members_3: "Shyam J",
    Team_Members_4: "Suraj S",
    Team_Members_5: "Tharun Deeksith K",
  },
  {
    id: 8,
    team_name: "HACK SQUAD HA^3",
    img: "images/Hacksquad.jpg",
    prize_category: "Most Popular Hack",
    Team_Members_1: "Harini P",
    Team_Members_2: "Almitha Dency J",
    Team_Members_3: "Archana M",
    Team_Members_4: "Arthi S",
    Team_Members_5: "Harini P",
  },
];
