export const winners = [
    {
        id: 0,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 2,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 3,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 4,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 5,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 6,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 7,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 8,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
    {
        id: 9,
        team_name : "",
        dept : "",
        img : "",
        prize_category : "",
        Team_Members_1 : "",
        Team_Members_2 : "",
        Team_Members_3 : "",
        Team_Members_4 : "",
        Team_Members_5 : "",
    },
      
  ];
  